.gitignore, README.md, pom.xml, src/main/java/net/unicon/lti/controller/app/TestController.java, src/main/java/net/unicon/lti/controller/app/TokenController.java, src/main/java/net/unicon/lti/controller/lti/AgsController.java, src/main/java/net/unicon/lti/controller/lti/JWKController.java, src/main/java/net/unicon/lti/controller/lti/LTI3Controller.java, src/main/java/net/unicon/lti/controller/lti/MembershipController.java, src/main/java/net/unicon/lti/controller/lti/OIDCController.java, src/main/java/net/unicon/lti/controller/lti/RegistrationController.java, src/main/java/net/unicon/lti/service/lti/LTIDataService.java, src/main/java/net/unicon/lti/service/lti/impl/LTIDataServiceImpl.java, src/main/java/net/unicon/lti/service/lti/impl/LTIJWTServiceImpl.java, src/main/java/net/unicon/lti/utils/lti/LTI3Request.java, src/main/resources/application.properties, src/test/java/net/unicon/lti/controller/lti/ConfigurationControllerTest.java, src/test/java/net/unicon/lti/controller/lti/LTI3ControllerTest.java
- Added flags to turn on/off the unimplemented services, started setting up the middleware to send the id_token to goldilocks
- Added unit tests for lti3 controller
- Cleaned up implementation to put "demo mode off" as primary functionality with "demo mode on" as separate endpoint
This removes any security risk around having unused endpoints that are still reachable, and it begins the process of integrating the middleware with goldilocks by sending the LTI response to the goldilocks endpoint after completing the initial LTI Core handshake.
https://lumenlearning.atlassian.net/browse/L3-23
1. I set the `lti13.demoMode` value to `false` in the `application.properties` file and ensured that after clicking on a goldilocks lti link, this directed me to goldilocks and no demo UI displayed. …
=> L3-23 remove demo code

pom.xml, src/main/java/net/unicon/lti/controller/lti/LTI3Controller.java, src/main/java/net/unicon/lti/utils/lti/DeepLinkUtils.java, src/main/resources/application.properties
Upgraded to Java 16, fixed deprecation warnings, and smoke tested to ensure nothing broke.
This change should allow for easier Docker integration as well as higher quality, more secure code.
[L3-41 Java version upgrade](https://lumenlearning.atlassian.net/browse/L3-41)
1. Followed the instructions here to ensure that I was compiling/running locally using Java 16: https://codippa.com/install-openjdk16-macos/
2. Ensured that there were no new compile or run errors with the upgrade.
3. Clicked on the link to Goldilocks from the Common Cartridge and ensured that it still goes through the LTI 1.3 flow and returns the Goldilocks Error page.
4. Set the following variables to true in the application.properties file to turn the demo mode on, then went through the demo flow and ensured all output …
=> L3-41 Upgrade to java 16, remove deprecated use of Integer, fix bug in demo with redirect path

src/main/java/net/unicon/lti/repository/LtiContextRepository.java, src/main/java/net/unicon/lti/service/lti/impl/AdvantageAGSServiceImpl.java, src/main/java/net/unicon/lti/service/sqs/impl/SQSMessageReceiver.java, src/test/java/net/unicon/lti/service/lti/test/AdvantageAGSServiceTest.java, src/test/java/net/unicon/lti/service/sqs/test/SQSMessageReceiverTest.java
In the event that a score fails posting to the LMS with a non-2xx-successful status and an exception isn't thrown, the following lines will appear in the logs:
```
2022-01-10 10:19:44.268 ERROR 8859 --- [enerContainer-2] n.u.l.s.sqs.impl.SQSMessageReceiver      : Response Status: <value>: <name>
2022-01-10 10:19:44.268 ERROR 8859 --- [enerContainer-2] n.u.l.s.sqs.impl.SQSMessageReceiver      : Response Status Reason: <reason>
2022-01-10 10:19:44.268 ERROR 8859 --- [enerContainer-2] n.u.l.s.sqs.impl.SQSMessageReceiver      : Response Body: <body>
```
After failing to post the score for any reason, lines similar to the following will appear in the logs:
```
2022-01-11 13:02:25.824 ERROR 51419 --- [enerContainer-2] n.u.l.s.sqs.impl.SQSMessageReceiver      : Score failed to post to LMS: …
```
=> L3-64 Add more specific logging for GPB

src/main/java/net/unicon/lti/model/sqs/SQSLineItem.java, src/main/java/net/unicon/lti/service/sqs/impl/SQSMessageReceiver.java, src/test/java/net/unicon/lti/service/sqs/test/SQSMessageReceiverTest.java
In the JSON input to the SQS queue for posting grades with the middleware, the `line_item_url` field has been changed to be the `lineitem_url` field.
This change leads to more consistency between the middleware, Goldilocks, and the IMS specifcation.
[L3-63](https://lumenlearning.atlassian.net/browse/L3-63)
1. Ensure that an SQS queue has been setup and hooked up to the middleware. Also ensure that the middleware has been registered with the Canvas instance/course that will be used for testing.
2. Send a message to the SQS queue with the following JSON format: `{"client_id": "97140000000000230", "user_id": "4f3d12df-e1ae-484f-8b9a-b667864e8100", "deployment_id": "461:5440a08422ab1ee7794a0588b5e4cb4a094c4256", "issuer": "https://canvas.instructure.com", "line_item_url": …
=> L3-63 Change format of lineitem url field for SQS message to AGS for posting grades

src/main/java/net/unicon/lti/controller/lti/LTI3Controller.java, src/main/java/net/unicon/lti/controller/lti/OIDCController.java, src/main/java/net/unicon/lti/model/lti/dto/LoginInitiationDTO.java, src/main/java/net/unicon/lti/security/lti/LTI3OAuthProviderProcessingFilter.java, src/main/java/net/unicon/lti/utils/LtiStrings.java, src/main/java/net/unicon/lti/utils/lti/LTI3Request.java, src/main/java/net/unicon/lti/utils/lti/LtiOidcUtils.java, src/test/java/net/unicon/lti/controller/lti/LTI3ControllerTest.java, src/test/java/net/unicon/lti/controller/lti/OIDCControllerTest.java, src/test/java/net/unicon/lti/utils/lti/LTI3RequestTest.java, src/test/java/net/unicon/lti/utils/lti/LtiOidcUtilsTest.java
Moved validation of issuer, clientId, and deploymentId from OIDC request controller to LTI launch controller because the LTI 1.3 Core specification does not guarantee that the clientId or deploymentId will be available for validation until after the id_token has been retrieved.
This change will allow a tool have multiple deployments associated with a single issuer and/or clientId without receiving a validation error.
[L3-68](https://lumenlearning.atlassian.net/browse/L3-68)
1. Ensure there is a functional Developer Key for the lti-middleware in Canvas.
2. Using the same client id from this Developer Key, deploy the lti-middleware to two separate Canvas courses and retrieve the deploymentId from each.
3. Perform a POST on the /config endpoint of the middleware for each deployment …
=> L3-68 fix issue of not allowing multiple deployments

README.md, src/main/java/net/unicon/lti/config/ApplicationConfig.java, src/main/java/net/unicon/lti/service/sqs/impl/SQSMessageReceiver.java, src/main/resources/application.properties, src/test/java/net/unicon/lti/service/sqs/test/SQSMessageReceiverTest.java
I added relatively simple steps that can be taken to disable the AWS integration for local development environments.
This solves the issue of developers needing valid AWS credentials and a valid SQS queue setup to be able to run the middleware locally (or else having to comment out large chunks of code).
[L3-67](https://lumenlearning.atlassian.net/browse/L3-67)
1. I commented out all of the `cloud.aws` properties in the properties file to remove my AWS credentials from my local setup.
2. I attempted to run `mvn clean install spring-boot:run` to start the local dev environment, and noticed the failure.
3. I followed the steps in the new README section titled "Turning off AWS Integration for Local Development" (Ran`export spring_profiles_active=no-aws` to set env var and uncommented …
=> L3-67 add the ability to turn off the aws integration for local development environments

src/main/java/net/unicon/lti/controller/lti/OIDCController.java, src/main/java/net/unicon/lti/utils/lti/LTI3Request.java, src/test/java/net/unicon/lti/controller/lti/OIDCControllerTest.java
Resolved issue where multiple deployments with the same clientId but different deploymentIds could not function simultaneously within Canvas. I also removed a red herring error from the logs regarding iframe size sometimes not being sent from the LMS in the id_token.
This solution is necessary for the tool to be able to be added on the class level in multiple instances within Canvas instead of on the account level.
[L3-68](https://lumenlearning.atlassian.net/browse/L3-68)
1. Ensure that the tool does not exist in the Canvas instance on the account level because this will lead to that tool being prioritized over the class level tools and its deployment information will always be provided instead of the class level deployment information. This can be done by going to Admin > Settings > Apps …
=> L3-68 Fix bug that disallowed multiple deployments

src/main/java/net/unicon/lti/service/lti/impl/LTIJWTServiceImpl.java
The aud in the token request JWT was being improperly set due to only checking for null instead of checking for both null and blank strings for the aud value in the config database table. This led to valid SQS messages not getting the grades posted back to the LMS. (I suspect that Canvas didn't used to validate the aud in this JWT and that they recently pushed an update to validate it, which is why this worked previously but not now.)
The fix for this solves the problem of valid SQS messages not resulting in grades being posted back to the LMS.
[L3-81](https://lumenlearning.atlassian.net/browse/L3-81
1. Send a valid SQS message to an SQS queue that is configured with the lti-middleware. For example: `{"client_id": "97140000000000230", "user_id": "4f3d12df-e1ae-484f-8b9a-b667864e8100", …
=> L3-81 fix ags token aud

src/main/java/net/unicon/lti/service/sqs/impl/SQSMessageReceiver.java, src/test/java/net/unicon/lti/service/sqs/test/SQSMessageReceiverTest.java
I updated the grade passback to accept the format sent by SNS and parse the lineitem message from there. The unit tests will be updated later this sprint and the solution will be cleaned up if needed.
This allows for grade passback to work when the message received by the SQS queue originally came from an SNS queue.
[L3-82](https://lumenlearning.atlassian.net/browse/L3-82)
1. Ensure that the middleware is configured to receive messages from an SQS queue.
2. Send a message to the SQS queue in the following format:
```
{
"Type" : "Notification",
"MessageId" : "f85561b6-dd51-5de6-8d75-3b128d9598d5",
"TopicArn" : "arn:aws:sns:us-west-2:725843923591:develop-lti13_grade",
"Message" : "{\"user_id\":\"4f3d12df-e1ae-484f-8b9a-b667864e8100\",\"lineitem_url\":\"https://canvas.unicon.net/api/lti/cours …
```
=> L3-82 Update AGS format for SNS, comment out unit tests temporarily

README.md, src/test/java/net/unicon/lti/service/sqs/test/SQSMessageReceiverTest.java
Updated unit tests to use the expected SNS format of posting grades back to the LMS, added a test to expect failure in the case of using purely the SQS json block alone. Also updated the README file's example AGS JSON to use the SNS format.
The update for using the new format needed the unit tests updated as well to ensure that each use case still functions as expected and to ensure no breaking changes are made in the future. Updating the format in the README will be helpful to developers working with the grade passback functionality in the future.
[L3-82](https://lumenlearning.atlassian.net/browse/L3-82)
1. Ensure that all of the SQSReceiver unit tests run and that the build still passes.
---
=> L3-82 Update unit tests for new SNS AGS format, update readme with new AGS format

pom.xml, src/main/java/net/unicon/lti/controller/lti/OIDCController.java, src/main/java/net/unicon/lti/security/lti/LTI3OAuthProviderProcessingFilter.java, src/main/java/net/unicon/lti/utils/TextConstants.java, src/main/java/net/unicon/lti/utils/lti/LTI3Request.java, src/test/java/net/unicon/lti/controller/lti/OIDCControllerTest.java, src/test/java/net/unicon/lti/security/lti/LTI3OAuthProviderProcessingFilterTest.java, src/test/java/net/unicon/lti/utils/lti/LTI3RequestTest.java
I switched from session storage to cookie storage for the state and nonce used to do the LTI Core authentication process. I also bumped the Spring version in light of the latest vulnerability (though this is simply precautionary as I believe either Spring MVC or Spring WebFlux is used in this project).
Switching from session storage to cookie storage will hopefully allow for having multiple instances of the middleware running without having to utilize sticky sessions. By storing the state and nonce in cookies in the user's browser, they remain tied to the user's browser without being tied to the session storage of a specific instance of the middleware.
[L3-93](https://lumenlearning.atlassian.net/browse/L3-93)
1. Run the middleware with demo mode off.
2. Log into Canvas and click on a …
=> L3-93 Switched from session storage to cookie storage

.platform/00_nginx.config, .platform/nginx/conf.d/proxy.conf, deploy/docker_beanstalk_deploy.sh
AWS configuration was updated to allow for larger headers to be able to set the state cookie.
This change was required so that the state and nonce could switch to being stored in cookies rather than in the Java session, which would have required sticky sessions.
[L3-93](https://lumenlearning.atlassian.net/browse/L3-93)
1. Log into a Canvas instance with the Lumen tool configured for the dev environment and navigate to a course with a cartridge for the dev environment.
2. Click on one of the links from the cartridge with the Network tab of the dev tools open.
3. Note that the LTI handshake completes without any 502 Bad Gateway errors occurring.
---
=> L3 93 ops changes for larger headers to set cookies

src/main/java/net/unicon/lti/service/lti/AdvantageConnectorHelper.java, src/main/java/net/unicon/lti/service/lti/impl/AdvantageAGSServiceImpl.java, src/main/java/net/unicon/lti/service/lti/impl/AdvantageConnectorHelperImpl.java, src/main/java/net/unicon/lti/utils/TextConstants.java, src/main/resources/templates/ltiAdvAgsMain.html
Ensure that the AGS demo functions in Moodle, D2L, and Canvas. This addresses the issue of Moodle returning JSON Bearer tokens with a content type of "text/html" as well as the issue of Moodle's lineitems URLs containing request parameters, unlike the rest of the LMSs.
These changes will allow for quicker experimentation with the AGS service for the "Deep Linking" effort.
[DL3-12](https://lumenlearning.atlassian.net/browse/DL3-12)
For each Moodle, D2L, and Canvas, do the following:
0. Ensure that the middleware is registered in the LMS and that there is a link within the LMS to access it. Ensure that both the demo mode and AGS features are turned on in the Middleware's `application.properties` file.
1. In the LMS, click on the link to the middleware.
2. Click the button to "Perform GET as …
=> Fix AGS demo for Moodle

src/main/java/net/unicon/lti/service/lti/impl/AdvantageAGSServiceImpl.java, src/main/java/net/unicon/lti/service/lti/impl/AdvantageConnectorHelperImpl.java, src/test/java/net/unicon/lti/service/lti/test/AdvantageAGSServiceTest.java, src/test/java/net/unicon/lti/service/lti/test/AdvantageConnectorHelperTest.java
Ensure that grade pass back works with Moodle. Addressed Moodle's issues of sending JSON tokens in the "text/html" format and including request parameters in its line item URLs.
It is unlikely that grade pass back worked with Moodle without this adjustments.
[L3-98](https://lumenlearning.atlassian.net/browse/L3-98)
For both Moodle and Canvas, do the following:
0. Ensure that the middleware is registered with the LMS and that a course exists with at least one user who has the Student role.
1. Submit a grade as a user with a Student role through the middleware. Note: The expected format for the submission to the SQS queue is as follows:
For Moodle:
```
{
"Type" : "Notification",
"MessageId" : "f85561b6-dd51-5de6-8d75-3b128d9598d5",
"TopicArn" : …
```
=> L3-98 Ensure that grade pass back works with Moodle

src/main/frontend/src/features/CoursePicker.js, src/main/frontend/src/features/LtiBreadcrumb.js
Remove References to Waymaker from the UI Text
Remove References to Waymaker from the UI Text
[Jira ticket](https://lumenlearning.atlassian.net/browse/DL3-32)
- Tested in the UI
- Searched the Waymaker string across all the source and it's not present in the UI anymore.
---
---
=> DL3-32 - Remove References to Waymaker from the UI Text

src/main/java/net/unicon/lti/controller/lti/LtiContextController.java, src/main/java/net/unicon/lti/service/harmony/HarmonyService.java, src/test/java/net/unicon/lti/controller/lti/LtiContextControllerTest.java, src/test/java/net/unicon/lti/service/harmony/HarmonyServiceTest.java
- Included the id_token in the body of the request to harmony for deep links.
- Included course_paired=false as a default request parameter of the request to harmony for deep links.
- Reduced number of String literals in unit tests in code cleanup effort
- Changed logging level from warn to error when parameters are missing for the deep link request
Adding the id_token to the body of the request will make it easier for Harmony to validate the customer account from which the request for deep links originated. Adding the course_paired=false parameter will also ensure that no breaking changes are introduced as the subsequent launch code is still under development. 
[DL3-51](https://lumenlearning.atlassian.net/browse/DL3-51)
Smoke test:
1. Ensure that you have an LMS course and that the tool …
=> DL3-51 Send id_token and course_paired=false by default when fetching deep links from harmony

src/main/java/net/unicon/lti/controller/lti/LtiContextController.java, src/main/java/net/unicon/lti/utils/lti/LTI3Request.java, src/test/java/net/unicon/lti/controller/lti/LtiContextControllerTest.java
I have now switched from using a global variable for the id_token to creating a method for the LTI3Request class that calls the constructor, allowing the unit tests to still function while not reusing old id_tokens on subsequent deep linking launches.
Mockito does not support mocking constructors. Initially, to avoid the need to mock the constructor for the id_token variable (lti3Request), I created a global variable for it. Unfortunately, this meant that this variable would stay in memory without getting overwritten for subsequent requests, leading to subsequent deep linking requests failing. I have now switched from using a global variable for the id_token to creating a method for the LTI3Request class that calls the constructor. Since Mockito supports mocking methods, the unit tests …
=> DL3-18 Fix unit test mocking strategy so that old id_tokens are not reused

src/main/frontend/src/App.css, src/main/frontend/src/features/CoursePreview.js, src/main/frontend/src/features/alerts/ErrorAlert.js
When a user clicks on 'Add Course' and there's an error with the request, displays a message informing the user about the issue.
When a user clicks on 'Add Course' and there's an error with the request, displays a message informing the user about the issue.
[Jira ticket](https://lumenlearning.atlassian.net/browse/DL3-39)
Tested locally without the backend, it always shows an error.
=> DL3-39 Display error message if deeplinks aren't successfully added

src/main/java/net/unicon/lti/service/harmony/HarmonyService.java, src/main/java/net/unicon/lti/utils/RestUtils.java, src/test/java/net/unicon/lti/service/harmony/HarmonyServiceTest.java
Added a workaround so that RestTemplate would be compatible with GET requests that include a body
This solves the problem of receiving a 422 error when trying to fetch Deep Links from Harmony without the id_token in the body.
[DL3-62](https://lumenlearning.atlassian.net/browse/DL3-62)
1. Ensure that the LMS course is configured to have access to the tool with Deep Linking.
2. Initiate the deep linking flow for a module in the LMS course.
3. Select the Lifespan Development course from the catalog since this one has links in it.
4. Click the "Add Course" button.
5. Wait 1-2 minutes for the links to be added to the LMS.
N/A
---
N/A
N/A
N/A
---
=> DL3-62 - Fix RestTemplate with GET body

src/main/java/net/unicon/lti/service/harmony/HarmonyService.java, src/main/resources/application-aws.properties, src/test/java/net/unicon/lti/service/harmony/HarmonyServiceTest.java
Switched from using a GET request to using a POST request when fetching Deep Links from Valkyrie.
Note: A GET request is still used when fetching the course catalog from Valkyrie.
This change is required because AWS does not always allow GET requests with a body, so we are preemptively switching these requests to be POST requests instead.
[DL3-64](https://lumenlearning.atlassian.net/browse/DL3-64)
Smoke testing to confirm that none of the current ipswich functionality has been removed:
1. Create a new course in the LMS and ensure that it has permission to use the registered tool for Deep Linking.
2. Start the deep linking flow within the course.
3. Select a course from the menu that has data (e.g. Lifespan Development).
4. Keep the Select All checked by default and click Add Course.
5. …
=> DL3-64 switch from get to post when fetching deep links

src/main/java/net/unicon/lti/controller/harmony/HarmonyRestController.java, src/main/java/net/unicon/lti/service/harmony/HarmonyService.java, src/test/java/net/unicon/lti/controller/harmony/HarmonyRestControllerTest.java, src/test/java/net/unicon/lti/service/harmony/HarmonyServiceTest.java
I added the ability for the lti-middleware backend to accept the `root_outcome_guid` parameter for the Valkyrie /course_catalog endpoint to be able to return a single course based upon this value.
This ensures maximal efficiency when skipping the course catalog page on the deep linking menu for subsequent launches when the LMS course has already been paired with a Lumen root_outcome_guid so that it can go straight to the course preview page for the paired course.
[DL3-75](https://lumenlearning.atlassian.net/browse/DL3-75)
Smoke testing to confirm that none of the current ipswich functionality has been removed:
1. Create a new course in the LMS and ensure that it has permission to use the registered tool for Deep Linking.
2. Start the deep linking flow within the course.
3. Select a course …
=> DL3-75 Add root_outcome_guid as request param when fetching course catalog

src/main/frontend/src/App.css, src/main/frontend/src/app/appSlice.js, src/main/frontend/src/features/CoursePicker.js, src/main/frontend/src/index.js
Shows an error when the Middleware provides a configured root_outcome_guid that does not match with any Harmony current course.
Displays the selected course when the backend sends to the frontend a previous root_outcome_guid.
The user can pair an LMS course with a Harmony course, then the Middleware will send to the frontend the root_outcome_guid , this value can be invalid if the course does not exist in the Harmony endpoint anymore.
[Jira ticket](https://lumenlearning.atlassian.net/browse/DL3-45)
This has been tested locally simulating all the possible combinations. 
When the previously selected course exists displays it.
When the previously selected course does not exist displays an error:
---
---
=> DL3-45 Display an error when the configured root_outcome_guid does not match any Harmony course

src/main/java/net/unicon/lti/controller/lti/RegistrationController.java, src/main/java/net/unicon/lti/service/lti/RegistrationService.java, src/main/java/net/unicon/lti/service/lti/impl/RegistrationServiceImpl.java, src/main/resources/application-aws.properties, src/main/resources/application.properties, src/test/java/net/unicon/lti/controller/lti/RegistrationControllerTest.java, src/test/java/net/unicon/lti/service/lti/test/RegistrationServiceTest.java
I updated the code to enable deep linking by default via Dynamic Registration, and I improved the debug logging statements for this code. I also researched the options for setting the deep linking menu dimensions during the configuration process and documented my findings in comments in the Jira ticket. Unfortunately, the deep linking menu dimensions cannot be set via Dynamic Registration, so I did not make any code changes for that.
This allows for there to be a lot fewer steps for admins who are configuring the Lumen tool to work with deep linking.
[DL3-40](https://lumenlearning.atlassian.net/browse/DL3-40)
1. Ensure that all of the environment variables for configuring the tool have unique values to the LMS.
2. Navigate to the LMS's Dynamic Registration page.
3. Enter the …
=> DL3-40 enable deep linking by default via dynamic registration

src/main/frontend/src/app/appSlice.js, src/main/frontend/src/features/CoursePreview.js, src/main/frontend/src/features/LtiBreadcrumb.js
When a course has been paired with the LMS and the user wants to add modules, it should skip the course catalog page. This PR also removes the breadcrumb and the cancel button so the user cannot select a different course.
It will prevent the user to cancel or go to the course catalog using the breadcrumb links.
[Jira ticket](https://lumenlearning.atlassian.net/browse/DL3-76)
Tested locally simulating the conditions and tested using D2L with a previously associated course.
In the following video the user access a linked course, displays the course preview and the breadcrumb and the cancel buttons are not present.
---
---
=> DL3-76 Returning User workflow- bread crumb and Cancel button improvements

src/main/frontend/public/index.html, src/main/frontend/src/index.js, src/main/java/net/unicon/lti/controller/lti/LTI3Controller.java, src/test/java/net/unicon/lti/controller/lti/LTI3ControllerTest.java
Indicate to the middleware front end if the LMS is Canvas to know if dynamic iframe sizing is supported.
This will allow for Canvas's window.postMessage feature to be used to dynamically change the size of the deep linking menu.
[DL3-86](https://lumenlearning.atlassian.net/browse/DL3-86)
1. I added console.log statements to index.js to output the `platform_family_code` variable.
2. I confirmed that when I opened the deep linking menu in Canvas, a value of `canvas` was output to the console.
3. I confirmed that when I opened the deep linking menu in D2L, a value of `desire2learn` was output to the console.
---
N/A
N/A
N/A
---
=> DL3-86 Indicate if the LMS is Canvas to the front end for dynamic iframe sizing

src/main/java/net/unicon/lti/controller/lti/LTI3Controller.java, src/test/java/net/unicon/lti/controller/lti/LTI3ControllerTest.java
Skips syncing lineitems for demo mode since demo links do not correspond to Lumen books.
Without this change, after inserting deep links from the demo picker, it was not possible to complete a standard LTI launch through the inserted links. With this change, the demo mode works as expected.
[DL3-4](https://lumenlearning.atlassian.net/browse/DL3-4)
Using a registered tool enabled in a course in the LMS, I went through the deep linking flow, inserted links, clicked on one of the links, went through the standard launch flow, opened the Memberships service and opened the AGS service, added an assignment using the AGS service.
N/A
---
N/A
N/A
N/A
---
=> DL3-4 do not sync lineitems for demo mode

README.md, src/main/java/net/unicon/lti/service/harmony/HarmonyService.java, src/main/resources/application-aws.properties, src/main/resources/application.properties, src/test/java/net/unicon/lti/service/harmony/HarmonyServiceTest.java
Removed the harmony JWT since the id_token will be used for auth instead.
This removes extraneous complexity from the code.
[DL3-65](https://lumenlearning.atlassian.net/browse/DL3-65)
The full deep linking flow will be tested in the dev-env once SP-199 is ready. It is not testable locally outside of the unit tests.
N/A
---
N/A
This must be deployed simultaneously with SP-199.
The `harmony.courses.jwt` variable has been removed.
---
=> DL3-65 remove harmony jwt

README.md, src/main/java/net/unicon/lti/config/WebSecurityConfig.java, src/main/java/net/unicon/lti/controller/app/MockValkyrieController.java, src/main/java/net/unicon/lti/controller/lti/LTI3Controller.java, src/main/java/net/unicon/lti/service/harmony/HarmonyService.java, src/main/resources/application-aws.properties, src/main/resources/application.properties, src/test/java/net/unicon/lti/controller/lti/LTI3ControllerTest.java, src/test/java/net/unicon/lti/service/harmony/HarmonyServiceTest.java
Lineitems are fetched from the LMS to be synced to Valkyrie on every launch (both standard LtiResourceLink launches and Deep Linking launches) except when the database indicates that the lineitems have already been synced. Upon receiving a root_outcome_guid from the lineitems sync for a course that doesn't already have one associated to it, I save the root_outcome_guid to the course and send it to the front end deep linking menu. I also set up INFO level logging for this feature and set the logging level for the AWS envs to INFO by default. Additionally, I added a MockValkyrieController to allow for local testing of the full integration flows.
This allows us to match the root_outcome_guid on Deep Linking launches so that in the case where a course has been copied, the course catalog can …
=> DL3-74 sync lineitems for returning DL users and add local mock valkyrie

src/main/frontend/src/App.js, src/main/frontend/src/features/CoursePicker.js, src/main/frontend/src/features/CoursePreview.js
Only display the loading screen when a course or modules have been selected, when courses are being loaded display a simple spinner like the previous version.
The loading screen should only be displayed when a course is being paired, not when courses are being loaded.
[Jira ticket](https://lumenlearning.atlassian.net/browse/DL3-82)
Tested locally simulating the scenarios. Tested against D2L using the DEV environment.
---
---
=> DL3-82 Limit the use of the loading screen in the Content Selector an

src/main/frontend/public/index.html, src/main/frontend/src/App.js, src/main/frontend/src/app/appSlice.js, src/main/frontend/src/index.js, src/main/java/net/unicon/lti/controller/lti/LTI3Controller.java, src/main/java/net/unicon/lti/utils/TextConstants.java, src/test/java/net/unicon/lti/controller/lti/LTI3ControllerTest.java
When there's an error syncing line items the frontend must display an error.
Provides an error message when there's an error syncing line items
[Jira ticket](https://lumenlearning.atlassian.net/browse/DL3-56)
Tested locally simulating the scenarios and tested against D2L.
---
---
=> DL3-56 Display error message if LINEITEMs aren't successfully synced to Harmony

src/main/java/net/unicon/lti/controller/lti/LTI3Controller.java, src/main/java/net/unicon/lti/exceptions/helper/MiddlewareErrorHandler.java, src/main/java/net/unicon/lti/utils/RestUtils.java, src/test/java/net/unicon/lti/controller/lti/LTI3ControllerTest.java
Bypassed Spring's default error handling so that the middleware's error handling would run.
This ensures that the error screens developed in DL3-56 appear when Valkyrie returns non-2xx response statuses or when Valkyrie doesn't return a response body when attempting to sync lineitems.
[DL3-92](https://lumenlearning.atlassian.net/browse/DL3-92)
1. As a prerequisite, I ensure that the tool was registered with the LMS and added to a course in the LMS and that links had been inserted from the tool to the LMS.
2. I commented out the mock Valkyrie lineitems endpoint to mimic Valkyrie returning a 404 when attempting to sync lineitems and redeployed my local environment.
3. I clicked on one of the links that had been inserted into my LMS course via deep linking and ensured that the error page …
=> DL3-92 fix resttemplate error handling

src/main/java/net/unicon/lti/service/lti/impl/RegistrationServiceImpl.java, src/test/java/net/unicon/lti/service/lti/test/RegistrationServiceTest.java
- filter by domain such that the Valkyrie middleware enables Deep Linking but not Waymaker
- Adjust the target link uri such that it correctly points to the /lti route, not the domain
- Environment changes to staging: domain.url set to https://goldilocks.ludev.team and LTI_MIDDLEWARE_NAME set to Lumen Waymaker 1.3 Staging
Fixes the target link uri for production and also fixes some config in staging environment as well. After conferring with Mary, the final say was that "Send Institution Role" is a non-critical setting that can't be configured dynamically via dynamic registration. Otherwise, the Assignment and Grade Services extension should be in place given how scopes are being assigned (accepting all supported scopes offered by LMS)
NOTE: production name has not been changed yet
[Jira …
=> WAYM-1626: Update LTI_MIDDLEWARE_NAME and Target URI values for Waymaker Dynamic Registration

src/main/java/net/unicon/lti/controller/lti/RegistrationController.java, src/main/java/net/unicon/lti/service/lti/impl/RegistrationServiceImpl.java
When I made the update to prioritize the middleware's error handling over Spring's method of throwing exceptions for any non-2xx response from REST calls, this broke the duplicate registration error handling because that was originally written expecting the non-2xx response to be included in the exception message instead of in the response body. This updates puts the response body with the appropriate message into the middleware's exception, allowing the correct error page to display in this case.
When there is an attempt to create a duplicate instance of a dynamic registration in D2L, the user should see an error message that indicates that this is the problem.
[DL3-90](https://lumenlearning.atlassian.net/browse/DL3-90)
0. As a prerequisite, ensure that your tool has already been …
=> DL3-90 fix duplicate registration error handling

src/main/frontend/src/App.css, src/main/frontend/src/App.js, src/main/frontend/src/features/CoursePicker.js, src/main/frontend/src/features/LoadingCoursesPage.js
When courses are loading do not display other components, just the spinner and the text.
Makes the loading screen cleaner, removing other controls.
[Jira ticket](https://lumenlearning.atlassian.net/browse/DL3-94)
Tested locally simulating the scenarios.
---
---
=> DL3-94 Updates to the course catalog and course preview loading screens

src/main/java/net/unicon/lti/controller/lti/LTI3Controller.java, src/main/java/net/unicon/lti/service/harmony/HarmonyService.java, src/test/java/net/unicon/lti/controller/lti/LTI3ControllerTest.java, src/test/java/net/unicon/lti/service/harmony/HarmonyServiceTest.java
I updated the middleware to not try to sync the lineitems if deep linking is disabled. I also added INFO logging to indicate that this is happening (please let me know if this is overkill for logging - it will be very easy to remove).
This ensures that there aren't errors when doing standard LTI core launches with deep linking disabled and no harmony API in place.
[DL3-97](https://lumenlearning.atlassian.net/browse/DL3-97)
1. Ensured that deep linking is enabled locally.
2. In a new course in the LMS that has access to my local tool, I went through the deep linking flow and inserted the links to my test course.
3. I clicked on one of the links I had inserted and ensured that the logs indicated that the lineitems syncing had taken place.
```
2022-09-22 16:18:12.479  INFO 18118 --- …
```
=> Dl3 97 do not sync lineitems if deep linking disabled
